version: '3.8'

services:
  mautic:
    image: mautic/mautic:latest
    container_name: mautic_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      MAUTIC_DB_HOST: db
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic_password
      MAUTIC_DB_NAME: mautic
      MAUTIC_TRUSTED_PROXIES: '["0.0.0.0/0"]'
    volumes:
      - mautic_data:/var/www/html
    restart: always
    platform: linux/amd64  # Specify platform explicitly

  db:
    image: mysql:5.7
    container_name: mautic_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mautic_password
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/amd64  # Specify platform explicitly
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  mautic_data:
  db_data:
